version: 0.2
env:
  runtime-versions:
    nodejs: 16
phases:
  install:
    commands:
      - node -v
      - npm -v
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'